#!/bin/bash

TARGET=$1
PING_LOG=$(mktemp --suffix=pingplot)
PLOT_DATA=$(mktemp --suffix=pingplot)

export TARGET
export PLOT_DATA

function clean_up () {
    trap '' EXIT ERR
    # Cleanup ping process
    kill $PING_PID
    # Cleanup files
    rm $PING_LOG -f
    rm $PLOT_DATA -f
}

function read_log () {
    while true
    do
        # Process last 100 lines of log file
        # Delete intro line (PING bbc.co.uk (212.58.244.22) 56(84) bytes of data.)
        # awk seq and time
        # remove labels and add tab
        tail -n100 $PING_LOG \
            | sed "/PING/d" \
            | awk '{print $5" "$7}' \
            | sed -e 's/icmp_seq=\|time=//g' -e 's/ /\t/' > $PLOT_DATA

        # Plot data
        gnuplot plot.gnu
        # Exit if something went wrong
        ret=$?
        if [ $ret -gt 0 ]; then
            exit 1
        fi

        sleep 1
    done
}

if [ -z $1 ]; then
    echo "$0 target"
    exit 1
fi

trap clean_up EXIT ERR

# -n numeric only needed for different verions of ping
ping $TARGET -n > $PING_LOG &
# Save PID for clean_up
PING_PID=$!

sleep 3 # 3 guarantees we have 2 data points

read_log
